### ISSUE TITLE
Download Result Model

### ISSUE THREAD

**Issue by TEKHOO** [EABogdanova/ProBAN#2]
I can't find best_model.pt in Result Model folder , how can i download it.

**Comment by TEKHOO** [comment]
I found the following comments in the code : Original file is located at https://colab.research.google.com/drive/1Ph-1Mz11biT0dIBtpC36Rr0fRPDXMg4Z. I can’t access this website. Is there something went wrong？

**Comment by EABogdanova** [comment]
I added a link to the model

**Comment by TEKHOO** [comment]
Thank you for your reply. I have successfully downloaded it and am ready to use it.  :)
